using Test
include("test_imports.jl")

@testset "ACMG Prototype" begin
    include("test_fparith.jl")
    include("test_ising.jl")
    include("test_sl2reps.jl")
    include("test_blocku.jl")
    include("test_stratum_enum.jl")
    include("test_block_u_general.jl")
    include("test_cyclotomic_context.jl")
    include("test_higher_central_charge.jl")
    include("test_io.jl")
    include("test_public_api.jl")
    include("test_fr_equations.jl")
    include("test_gauge.jl")
    include("test_finite_fields.jl")
    include("test_toric_gauge.jl")
    include("test_gauge_stabilizers.jl")
    include("test_fr_roundtrip.jl")
    include("test_pipeline_primes.jl")
    include("test_pipeline_end_to_end.jl")
    include("test_pipeline_rank23_smoke.jl")
    include("braid_representations.jl")
    include("braid_relations.jl")
    include("finite_field_braid.jl")
    include("fr_modp_semion.jl")
    include("fr_modp_fibonacci.jl")
    include("fr_modp_ising.jl")
    include("braid_modp_fibonacci.jl")
    include("braid_modp_ising.jl")
    include("zariski_diagnostics.jl")
    include("test_api_stability_docs.jl")
end
